# Generated by Django 5.1.5 on 2026-02-09 15:46

import backend.models.theme
import backend.models.user
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArgumentTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Other', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.argumentscheme')),
                ('theme', models.ForeignKey(default=backend.models.theme.ArgumentTheme.get_or_create_other_theme, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.argumenttheme')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.argumentscheme')),
            ],
        ),
        migrations.CreateModel(
            name='ArgumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacking', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('child_argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='backend.argumentscheme')),
                ('parent_argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='backend.argumentscheme')),
                ('critical_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.criticalquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='backend.argumentscheme')),
            ],
        ),
        migrations.CreateModel(
            name='ArgumentFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='backend.argument')),
                ('scheme_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.schemefield')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*\\d)', 'Password must contain at least one uppercase letter and one number.')])),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ArgumentVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upvote', models.BooleanField()),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='backend.argument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='argumenttheme',
            name='creator',
            field=models.ForeignKey(default=backend.models.user.User.deleted_user, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.user'),
        ),
        migrations.AddField(
            model_name='argumentscheme',
            name='created_by',
            field=models.ForeignKey(default=backend.models.user.User.deleted_user, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.user'),
        ),
        migrations.AddField(
            model_name='argument',
            name='author',
            field=models.ForeignKey(default=backend.models.user.User.deleted_user, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.user'),
        ),
    ]
