# Generated by Django 5.1.5 on 2026-02-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArgumentVotes',
            new_name='ArgumentVote',
        ),
    ]
