# Generated by Django 5.1.5 on 2026-02-25 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_argumentvotes_argumentvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*\\d).+$', 'Password must contain at least one uppercase letter and one number.')]),
        ),
    ]
