# Generated by Django 5.1.5 on 2026-03-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalquestion',
            name='two_way',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='argumentlink',
            name='child_argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='backend.argument'),
        ),
        migrations.AlterField(
            model_name='argumentlink',
            name='parent_argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='backend.argument'),
        ),
    ]
