# Generated by Django 5.1.5 on 2026-03-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_criticalquestion_two_way_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArgumentVote',
        ),
    ]
