# Generated by Django 5.1.5 on 2026-03-26 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_delete_argumentvote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemefield',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='argumentscheme',
            name='template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemefield',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criticalquestion',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_questions', to='backend.argumentscheme'),
        ),
        migrations.CreateModel(
            name='ThemeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
