# Generated by Django 5.1.5 on 2026-04-04 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_schemefield_options_argumentscheme_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_arguments', to=settings.AUTH_USER_MODEL),
        ),
    ]
