# Generated by Django 5.1.5 on 2026-04-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_argument_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='is_winning',
            field=models.BooleanField(default=True),
        ),
    ]
