# Generated by Django 5.1.5 on 2026-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_argument_is_winning'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
