# Generated by Django 5.1.5 on 2026-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_argument_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='is_winning',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
